// Projects-Data.js
export const projectsData = [
  {
    id: 1,
    title: "ProEv: Instructor Evaluation Profiling System with Facial Recognition",
    card_image: "/images/projects/proev/card.png",
    main_image: "/images/projects/proev/banner.png",
    image_01: "/images/projects/proev/face.png",
    image_02: "/images/projects/proev/front.png",
    image_03: "/images/projects/proev/stat.png",
    desc: "Digital platform with integrated facial recognition (AWS) with a secure profiling and evaluation.",
    tags: ["Facial-Recognition", "Evaluation", "Profiling"],
    core_technologies: ["React", "NodeJS", "AWS Rekognition", "Tailwind CSS"],
    github_link: "https://github.com/yourusername/instructor-eval",
    demo_link: "#",
    isPlaceholder: false
  },
  {
    id: 2,
    title: "Barangay Records System",
    card_image: "/images/mapro.png",
    main_image: "/images/mapro-main.png",
    image_01: "/images/mapro-stats.png",
    image_02: "/images/mapro-logs.png",
    image_03: "", // Add Module 3 path here
    desc: "Streamlined operations hub for citizen data, automated statistics, and transaction logging.",
    tags: ["Automation", "Public", "Statistics"],
    core_technologies: ["PHP Laravel", "MySQL", "Chart.js", "Bootstrap"],
    github_link: "https://github.com/yourusername/barangay-records",
    demo_link: "#",
    isPlaceholder: false
  },
  {
    id: 3,
    title: "Petmosphere",
    card_image: "/images/pet-bg.jpg",
    main_image: "/images/pet-main.png",
    image_01: "/images/pet-adopt.png",
    image_02: "/images/pet-user.png",
    image_03: "", // Add Module 3 path here
    desc: "Centralized online adoption hub connecting future pet parents with animals in need.",
    tags: ["Adoption", "Webapp", "Centralized"],
    core_technologies: ["React", "Firebase", "Framer Motion", "Tailwind"],
    github_link: "https://github.com/yourusername/petmosphere",
    demo_link: "#",
    isPlaceholder: false
  },
  {
    id: 4,
    title: "AI. Cookmate",
    card_image: "/images/cookmate.png",
    main_image: "/images/cookmate-main.png",
    image_01: "/images/cookmate-chat.png",
    image_02: "/images/cookmate-recipe.png",
    image_03: "", // Add Module 3 path here
    desc: "AI Kitchen Assistant using natural language chat to generate and personalize recipes.",
    tags: ["AI", "LLM", "Chatbot"],
    core_technologies: ["Next.js", "Groq AI", "Node.js", "PostgreSQL"],
    github_link: "https://github.com/yourusername/cookmate",
    demo_link: "#",
    isPlaceholder: false
  },
  {
    id: 5,
    title: "Procurement Management",
    card_image: "/images/procurement-bg.jpg",
    main_image: "/images/procurement-main.png",
    image_01: "/images/procurement-inv.png",
    image_02: "/images/procurement-flow.png",
    image_03: "", // Add Module 3 path here
    desc: "ERP solution for BCJ Logistics to automate requisition, inventory, and procurement workflows.",
    tags: ["ERP", "Management", "Logistics"],
    core_technologies: ["React", "Laravel", "PostgreSQL", "Inertia.js"],
    github_link: "https://github.com/yourusername/procurement",
    demo_link: "#",
    isPlaceholder: false
  },
  {
    id: 6,
    title: "Unit Battle Simulator",
    card_image: "/images/projects/uniitb/battle.png",
    main_image: "/images/projects/uniitb/battle.png",
    image_01: "/images/projects/uniitb/datas.png",
    image_02: "/images/projects/uniitb/range.png",
    image_03: "/images/projects/uniitb/select.png",
    desc: "A red-vs-blue sandbox simulator built for strategic unit battle testing I made for fun.",
    tags: ["Game", "Simulator", "Battle"],
    core_technologies: ["Javascript", "HTML & CSS"],
    github_link: "https://github.com/yourusername/unit-battle",
    demo_link: "https://rexshimura.github.io/unit_battle_simulator/",
    isPlaceholder: false
  },
  // --- PAGE 2: PLACEHOLDERS ---
  {
    id: 7,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "Currently in the conceptual phase. Development scheduled for upcoming sprint.",
    tags: ["Research", "Development"],
    core_technologies: ["TBA", "Conceptual"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  },
  {
    id: 8,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "System architecture being finalized. Module integration pending.",
    tags: ["TBA"],
    core_technologies: ["TBA"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  },
  {
    id: 9,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "System architecture being finalized. Module integration pending.",
    tags: ["TBA"],
    core_technologies: ["TBA"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  },
  {
    id: 10,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "System architecture being finalized. Module integration pending.",
    tags: ["TBA"],
    core_technologies: ["TBA"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  },
  {
    id: 11,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "System architecture being finalized. Module integration pending.",
    tags: ["TBA"],
    core_technologies: ["TBA"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  },
  {
    id: 12,
    title: "Project N/A",
    card_image: "",
    main_image: "",
    image_01: "",
    image_02: "",
    image_03: "",
    desc: "System architecture being finalized. Module integration pending.",
    tags: ["TBA"],
    core_technologies: ["TBA"],
    github_link: "#",
    demo_link: "#",
    isPlaceholder: true
  }
];